### ISSUE TITLE
Fix variable expansion

### ISSUE THREAD

**Issue by abaez** [fisherman/paths#2]
As detailed on [a comment by Jorge][1], the variable expansion isn't necessarily working. Right now a variable would only be assigned in name but not by it's value when aggregating to the environment. So if we have a variable name `$HOME` and its expansion would be `/home/user`, the variable name would be used only and not the expansion.

The correct aggregation would be to have `$HOME` expanded when added to the environment.:

``` fish
set -gx HOME /home/user
```
instead of 

``` fish
set -gx HOME $HOME
```

[1]: https://github.com/fisherman/paths/pull/1#issuecomment-220070709

**Comment by Bj** [comment]
Not a trivial feature, but definitely a must have.

**Comment by abaez** [comment]
I'll work on it later today. Hopefully have something fruitful by the end of it.

**Comment by Bj** [comment]
Go for it :)

**Comment by brj** [comment]
https://github.com/fisherman/paths/commit/1e309f8eba479d773d36c22a8cba5e339449c119

:)

Any variable from your environment is expanded now. This opens a backdoor for injecting a malicious script in any of your paths.d files, however, so I don't consider this a final solution to the issue.

**Comment by brj** [comment]
Alas, we can't have variable expansion and be safe and be fast at the same time, so I went with safe and fast.

**Comment by abaez** [comment]
I think it's a great compromise. Plus side is that `$PATH` now is not the only variable who can have easy to append list.

**Comment by fazibear** [comment]
Is this feature working ? 

tried:

```
echo \$HOME/test > paths.d/test
```

with no luck

```
test=$HOME/test
```
