### ISSUE TITLE
[RFC] No append for declared environment variables.

### ISSUE THREAD

**Issue by abaez** [fisherman/paths#4]
After looking at the environment variables, I noticed that many of the values whom shouldn't extend, were doing so. As an example. Say I was defining the `$EDITOR` variable. When I would run `env | grep $EDITOR`, I would get the variable definition:

``` ini
EDITOR=nvim  nvim
```

Instead of:

``` ini
EDITOR=nvim
```

This is due to the variable already having a declaration elsewhere. As such, the variable would be appended instead of replacing the environment variable.  This can be remedied by removing the extend factor on the declaration. Thus, I'm requesting for the variable declaration to not have aggregation.

**Comment by brj** [comment]
Sounds reasonable. Let me get to this after #1 #2 and #3.

**Comment by brj** [comment]
https://github.com/fisherman/paths/commit/1e309f8eba479d773d36c22a8cba5e339449c119

:)
